{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.tls }}

{{- range .Values.ingress.tls }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .secretName }}
spec:
  secretName: {{ .secretName}}
  dnsNames:
  {{- range .hosts }}
  - {{ . | quote }}
  {{- end }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
{{- end }}

{{- end }}
{{- end }}
