# Default values for pycon-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: searegistry.azurecr.io/pycon-indonesia
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  hosts:
    - pycon-staging.southeastasia.cloudapp.azure.com
    - pycon-staging.apps.readon.ly
  tls:
    - secretName: tls-secret
      hosts:
        - pycon-staging.southeastasia.cloudapp.azure.com
    - secretName: pycon-staging-tls-secret
      hosts:
        - pycon-staging.apps.readon.ly

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
