# Default values for pycon-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  frontend: 2
  backend: 3

image:
  tag: latest
  backend:
    repository: searegistry.azurecr.io/pycon-backend
    pullpolicy: ifnotpresent
  frontend:
    repository: searegistry.azurecr.io/pycon-frontend
    pullpolicy: ifnotpresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
#     nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  hosts:
    - pycon-staging.southeastasia.cloudapp.azure.com
    - pycon-staging.apps.readon.ly
  tls:
    - secretName: tls-secret
      hosts:
        - pycon-staging.southeastasia.cloudapp.azure.com
    - secretName: pycon-staging-tls-secret
      hosts:
        - pycon-staging.apps.readon.ly

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}
